version: "3.9"
services:
  service1:
    build: ./service1
    depends_on: # makes sure service1 starts after service2 and storage
      - service2
      - storage
    ports: 
       - "8199:5000"
    networks: 
      - hostNetwork
      - internalNetwork
    volumes:
      # because we already have a local file vstorage on the host machine it will be used as a file ;) hackmac
      - ./vstorage:/vstorage:w  # shared volume with service2 - local folder on host machine - write

  service2:
    build: ./service2
    depends_on: # makes sure service2 starts after storage
      - storage
    networks: 
      - internalNetwork
    volumes:
    # because we already have a local file vstorage on the host machine it will be used as a file ;) hackmac
      - ./vstorage:/vstorage:w # shared volume with service1 - local folder on host machine - write

  storage:
    build: ./storage
    networks:
      - internalNetwork
    volumes:
      - storage:/storage:rw # own volume - read/write

networks:
  hostNetwork:
    driver: bridge      # default! - Accessible from outside the Docker Container (e.g.: via localhost and port mapping)
  internalNetwork:
    # internal! isolates the network from the outside world
    driver: bridge      # default! - Bridge networks are commonly used when your application runs in a container that needs to communicate with other containers on the same host
    internal: true      # other services inside the container can access it - but not from outside the container
    attachable: false   # other containers can attach to this network

volumes:
  storage: # only for the storage service