version: "3.9"
services:
  service1:
    build: ./service1-js
    ports: 
       - "8199:5000"
    networks: 
      - internalNetwork
    volumes:
      - vstorage:/vstorage

  service2:
    build: ./service2-python
    networks: 
      - internalNetwork
    volumes:
      - vstorage:/vstorage

  storage:
    build: ./storage
    networks:
      - internalNetwork
    volumes:
      - vstorage:/vstorage

networks:
  internalNetwork:
    # internal! isolates the network from the outside world
    driver: bridge

volumes:
  vstorage: