version: "3.9"
services:
  service1:
    build: ./service1-js
    depends_on: # makes sure service1 starts after service2 and storage
      - service2
      - storage
    ports: 
       - "8199:5000"
    networks: 
      - internalNetwork
    volumes:
      # because we already have a local file vstorage on the host machine it will be used as a file ;) hackmac
      - ./vstorage:/vstorage:w  # shared volume with service2 - local folder on host machine - write

  service2:
    build: ./service2-python
    depends_on: # makes sure service2 starts after storage
      - storage
    networks: 
      - internalNetwork
    volumes:
    # because we already have a local file vstorage on the host machine it will be used as a file ;) hackmac
      - ./vstorage:/vstorage:w # shared volume with service1 - local folder on host machine - write

  storage:
    build: ./storage
    networks:
      - internalNetwork
    volumes:
      - storage:/storage:rw # own volume - read/write

networks:
  internalNetwork:
    # internal! isolates the network from the outside world
    driver: bridge

volumes:
  storage: # only for the storage service